<script setup>
import { h } from 'vue'
import { ArrowLeft, CalendarDays, Check, CirclePlus, Clock3, CookingPot, NotebookPen, Plus, Trash2 } from '@lucide/vue'
import { NButton as Button, NInput as Textarea, NSelect as Select } from 'naive-ui'
import { usePlannerStore } from '../stores/planner'
import { dayName, dayNumber, mealParts, mealSlots, mealImageUrl, periodRange } from '../utils/planner'

const planner = usePlannerStore()
function renderMealLabel(option) { return h('span', { class: 'meal-option-label' }, [option.image ? h('img', { src: option.image, alt: '', class: 'meal-option-image' }) : h(CookingPot, { size: 17, 'aria-hidden': 'true' }), h('span', option.label)]) }
</script>

<template>
  <section v-if="planner.selectedDay" :key="planner.selectedDay.date" class="day-detail">
    <div class="detail-heading"><Button class="no-print" quaternary @click="planner.selectedDayIndex = null"><ArrowLeft :size="18" /><span>{{ planner.weekLabel }}</span></Button><div><p class="eyebrow">Daily plan</p><h2>{{ dayName(planner.selectedDay) }}, {{ dayNumber(planner.selectedDay) }}</h2><span v-if="planner.availabilityFor(planner.selectedDay)" class="availability">{{ planner.availabilityFor(planner.selectedDay) }}</span></div></div>
    <div class="detail-layout">
      <div class="duty-editor"><section v-for="period in planner.periods" :key="period.id" class="period-section"><div class="section-heading"><div><p class="period-time"><Clock3 :size="15" /> {{ periodRange(period) }}</p><h3>{{ period.label }}</h3></div><Button class="no-print" quaternary size="small" @click="planner.addDuty(planner.selectedDay, period.id)"><CirclePlus :size="17" /><span>Add duty</span></Button></div><div v-if="!planner.dutiesFor(planner.selectedDay, period.id).length" class="empty-line">No duties planned</div><article v-for="duty in planner.dutiesFor(planner.selectedDay, period.id)" :key="duty.id" class="duty-row" :data-assignee="duty.assignee.toLowerCase()"><div class="duty-choice"><span class="duty-emoji" aria-hidden="true">{{ planner.dutyEmoji(duty) }}</span><Select class="duty-select" :value="duty.sourceId" :options="planner.dutyOptions" filterable tag aria-label="Duty or new duty" @update:value="planner.changeDuty(duty, $event)" /></div><Select :value="duty.period" :options="planner.periodOptions" aria-label="Routine Period" @update:value="planner.changeDutyPeriod(duty, $event)" /><Select v-model:value="duty.time" :options="planner.timeOptionsFor(duty.period)" clearable placeholder="Optional time" aria-label="Optional exact time" /><Select v-model:value="duty.assignee" :options="planner.assigneeOptions" aria-label="Assigned to" /><Button class="no-print" quaternary circle type="error" aria-label="Remove duty" @click="planner.removeDuty(planner.selectedDay, duty.id)"><Trash2 :size="17" /></Button></article></section></div>
      <aside class="meal-editor"><section v-if="planner.calendarEventsFor(planner.selectedDay).length" class="calendar-event-list"><div class="section-heading"><div><p class="period-time"><CalendarDays :size="15" /> Google Calendar</p><h3>Calendar</h3></div></div><div v-for="event in planner.calendarEventsFor(planner.selectedDay)" :key="event.id" class="calendar-event"><div><strong>{{ event.title }}</strong><span>{{ planner.calendarEventTime(event) }}</span></div><Button class="no-print" quaternary circle :disabled="planner.calendarEventIsCopied(planner.selectedDay, event)" :aria-label="planner.calendarEventIsCopied(planner.selectedDay, event) ? `${event.title} added` : `Add ${event.title} to duties`" :title="planner.calendarEventIsCopied(planner.selectedDay, event) ? 'Added' : 'Add to duties'" @click="planner.copyCalendarEvent(planner.selectedDay, event)"><Check v-if="planner.calendarEventIsCopied(planner.selectedDay, event)" :size="17" /><Plus v-else :size="17" /></Button></div></section><p v-if="planner.calendarEventsError" class="calendar-event-error">{{ planner.calendarEventsError }}</p><div class="section-heading"><div><p class="period-time"><CookingPot :size="15" /> Meal plan</p><h3>Meals</h3></div></div><section v-for="slot in mealSlots" :key="slot.id" class="meal-slot"><h4>{{ slot.label }}</h4><div class="meal-fields"><label v-for="part in mealParts" :key="part.id"><span>{{ part.label }}</span><Select v-model:value="planner.selectedDay.meals[slot.id][part.id]" :options="planner.mealOptions(part.id)" :render-label="renderMealLabel" filterable clearable :placeholder="`No ${part.label.toLowerCase()}`" /></label><label><span>Prepared by</span><Select v-model:value="planner.selectedDay.meals[slot.id].assignee" :options="planner.assigneeOptions" /></label></div></section><label class="notes-field"><span><NotebookPen :size="16" /> Notes for the day</span><Textarea v-model:value="planner.selectedDay.notes" type="textarea" autosize :rows="3" placeholder="Add a reminder…" /></label></aside>
    </div>
  </section>
</template>