<script setup>
import { computed, ref } from 'vue'
import { ArrowDown, ArrowUp, CalendarDays, CirclePlus, Clock3, CookingPot, House, ImagePlus, ListPlus, Pencil, Trash2, X } from '@lucide/vue'
import { NButton as Button, NCard, NCheckbox as Checkbox, NInput as InputText, NModal, NSelect as Select, useMessage } from 'naive-ui'
import { usePlannerStore } from '../stores/planner'
import { allTimeOptions, cloneData, dutyEmojiOptions, householdIconOptions, mealImageUrl, mealParts, periodEndOptions, suggestedDutyEmoji, weekdays } from '../utils/planner'

const open = defineModel('open', { type: Boolean, default: false })
const planner = usePlannerStore()
const message = useMessage()
const optionMode = ref('household')
const newDuty = ref({ name: '', area: '', emoji: '' })
const newMeal = ref({ name: '', type: 'main', image: null })
const newAssignee = ref('')
const routineError = ref('')
const editingOption = ref(null)
const imageError = ref('')
const googleCalendars = ref([])
const selectedGoogleCalendar = ref(null)
const googleCalendarError = ref('')
const googleCalendarBusy = ref(false)
const canManageGoogleCalendar = computed(() => ['localhost', '127.0.0.1', '::1'].includes(window.location.hostname))

// Stage a valid Assignee name before it becomes part of the Household form.
function addAssignee() { const name = newAssignee.value.trim(); planner.addAssignee(name); newAssignee.value = '' }
// Save Routine Period and availability edits through the Household record.
async function saveRoutine() { await planner.saveHousehold(); routineError.value = planner.householdError }
// Reset each catalog form only after its option has been persisted.
async function addDutyOption() { await planner.addDutyOption(newDuty.value); newDuty.value = { name: '', area: '', emoji: '' } }
async function addMealOption() { await planner.addMealOption(newMeal.value); newMeal.value = { name: '', type: 'main', image: null } }
// Work on an independent draft so catalog rows are not changed until Save.
function startEditOption(kind, option) { editingOption.value = { kind, originalId: option.id, ...cloneData(option) } }
async function commitOptionEdit() { await planner.commitOptionEdit(editingOption.value); editingOption.value = null }
// Process and upload Media Assets before retaining only the returned filename in planner state.
async function handleMealImage(event, target) {
  const [file] = event.target.files
  if (!file) return
  imageError.value = ''
  try { target.image = await planner.uploadMealImage(file) } catch (error) { imageError.value = error.message; message.error(error.message) } finally { event.target.value = '' }
}
async function loadGoogleCalendars() {
  googleCalendarBusy.value = true; googleCalendarError.value = ''
  try { googleCalendars.value = await planner.googleCalendarCalendars() }
  catch (error) { googleCalendarError.value = error.message }
  finally { googleCalendarBusy.value = false }
}
function connectGoogleCalendar() { window.location.assign('/api/integrations/google/connect') }
async function selectGoogleCalendar() {
  if (!selectedGoogleCalendar.value) return
  googleCalendarBusy.value = true; googleCalendarError.value = ''
  try { await planner.selectGoogleCalendar(selectedGoogleCalendar.value); googleCalendars.value = [] }
  catch (error) { googleCalendarError.value = error.message }
  finally { googleCalendarBusy.value = false }
}
async function disconnectGoogleCalendar() {
  googleCalendarBusy.value = true; googleCalendarError.value = ''
  try { await planner.disconnectGoogleCalendar(); selectedGoogleCalendar.value = null; googleCalendars.value = [] }
  catch (error) { googleCalendarError.value = error.message }
  finally { googleCalendarBusy.value = false }
}
</script>

<template>
  <NModal v-model:show="open"><NCard class="modal-card options-card" title="Manage planner options" role="dialog" aria-modal="true" closable @close="open = false">
    <div class="option-switch"><Button :type="optionMode === 'household' ? 'primary' : 'default'" @click="optionMode = 'household'"><House :size="17" /> Household</Button><Button :type="optionMode === 'routine' ? 'primary' : 'default'" @click="optionMode = 'routine'"><Clock3 :size="17" /> Routine</Button><Button :type="optionMode === 'duties' ? 'primary' : 'default'" @click="optionMode = 'duties'"><ListPlus :size="17" /> Duties</Button><Button :type="optionMode === 'meals' ? 'primary' : 'default'" @click="optionMode = 'meals'"><CookingPot :size="17" /> Meals</Button><Button :type="optionMode === 'integrations' ? 'primary' : 'default'" @click="optionMode = 'integrations'"><CalendarDays :size="17" /> Integrations</Button></div>
    <template v-if="optionMode === 'household'"><form class="household-form" @submit.prevent="planner.saveHousehold"><label><span>Home name</span><InputText v-model:value="planner.household.name" placeholder="My Home" aria-label="Home name" /></label><label><span>Icon</span><Select v-model:value="planner.household.icon" :options="householdIconOptions" aria-label="Home icon" /></label><div class="assignee-fields"><span>Assignees</span><div v-for="(assignee, index) in planner.household.assignees" :key="`${assignee}-${index}`" class="assignee-row"><InputText :value="assignee" :disabled="planner.assigneeInUse(assignee)" :title="planner.assigneeInUse(assignee) ? 'Move planned work before renaming this Assignee' : undefined" :aria-label="`${assignee} name`" @update:value="planner.renameAssignee(index, $event)" /><Button quaternary circle type="error" :disabled="planner.household.assignees.length === 1 || planner.assigneeInUse(assignee)" :title="planner.assigneeInUse(assignee) ? 'Move planned work before removing this Assignee' : undefined" :aria-label="`Remove ${assignee}`" @click="planner.removeAssignee(assignee)"><X :size="16" /></Button></div><div class="add-assignee"><InputText v-model:value="newAssignee" placeholder="Add a person" aria-label="New Assignee name" @keyup.enter.prevent="addAssignee" /><Button secondary @click="addAssignee"><CirclePlus :size="17" /> Add</Button></div></div><p v-if="planner.householdError" class="form-error">{{ planner.householdError }}</p><div class="modal-actions"><Button type="primary" attr-type="submit">Save household</Button></div></form></template>
    <template v-else-if="optionMode === 'routine'"><div class="routine-editor"><div class="section-heading"><div><p class="period-time"><Clock3 :size="15" /> Daily routine</p><h3>Routine periods</h3></div><Button secondary :disabled="planner.household.routinePeriods.length === 6" @click="planner.addRoutinePeriod"><CirclePlus :size="17" /> Add period</Button></div><article v-for="(period, index) in planner.household.routinePeriods" :key="period.id" class="routine-row"><InputText v-model:value="period.label" aria-label="Routine Period name" /><Select v-model:value="period.start" :options="allTimeOptions" aria-label="Routine Period start time" /><Select v-model:value="period.end" :options="periodEndOptions" aria-label="Routine Period end time" /><div class="row-actions"><Button quaternary circle :disabled="index === 0" aria-label="Move Routine Period earlier" @click="planner.moveRoutinePeriod(index, -1)"><ArrowUp :size="16" /></Button><Button quaternary circle :disabled="index === planner.household.routinePeriods.length - 1" aria-label="Move Routine Period later" @click="planner.moveRoutinePeriod(index, 1)"><ArrowDown :size="16" /></Button><Button quaternary circle type="error" :disabled="planner.household.routinePeriods.length === 2 || planner.periodInUse(period.id)" :title="planner.periodInUse(period.id) ? 'Move planned Duties before removing this Routine Period' : undefined" aria-label="Remove Routine Period" @click="planner.removeRoutinePeriod(index)"><Trash2 :size="16" /></Button></div></article><div class="off-day-fields"><p>Days off</p><div v-for="assignee in planner.household.assignees" :key="assignee" class="off-day-row"><strong>{{ assignee }}</strong><Checkbox v-for="weekday in weekdays" :key="weekday.value" :checked="planner.household.offDays[assignee]?.includes(weekday.value)" @update:checked="planner.setOffDay(assignee, weekday.value, $event)">{{ weekday.label }}</Checkbox></div></div><p v-if="routineError" class="form-error">{{ routineError }}</p><div class="modal-actions"><Button type="primary" @click="saveRoutine">Save routine</Button></div></div></template>
    <template v-else-if="optionMode === 'duties'"><form class="option-form duty-option-form" @submit.prevent="addDutyOption"><InputText v-model:value="newDuty.name" placeholder="Duty name" aria-label="Duty name" /><InputText v-model:value="newDuty.area" placeholder="Area, e.g. Kitchen" aria-label="Duty area" /><Select v-model:value="newDuty.emoji" :options="dutyEmojiOptions" clearable placeholder="Suggested" aria-label="Duty emoji" /><Button attr-type="submit"><CirclePlus :size="18" /> Add</Button></form><div class="option-list"><div v-for="duty in planner.catalog.duties" :key="duty.id" class="option-row"><template v-if="editingOption?.kind === 'duty' && editingOption.originalId === duty.id"><div class="option-edit-fields"><span class="duty-emoji duty-edit-preview" aria-hidden="true">{{ editingOption.emoji || suggestedDutyEmoji(editingOption.name) }}</span><InputText v-model:value="editingOption.name" /><InputText v-model:value="editingOption.area" /><Select v-model:value="editingOption.emoji" :options="dutyEmojiOptions" clearable aria-label="Duty emoji" /><Button size="small" @click="commitOptionEdit">Save</Button></div></template><template v-else><div class="option-identity"><span class="duty-emoji" aria-hidden="true">{{ duty.emoji || suggestedDutyEmoji(duty.name) }}</span><div><strong>{{ duty.name }}</strong><span>{{ duty.area }}</span></div></div><div class="row-actions"><Button quaternary circle aria-label="Rename duty" @click="startEditOption('duty', duty)"><Pencil :size="16" /></Button><Button quaternary circle type="error" aria-label="Delete duty option" @click="planner.deleteOption('duty', duty.id)"><Trash2 :size="16" /></Button></div></template></div></div></template>
    <template v-else><form class="option-form meal-option-form" @submit.prevent="addMealOption"><InputText v-model:value="newMeal.name" placeholder="Meal name" aria-label="Meal name" /><Select v-model:value="newMeal.type" :options="mealParts.map((part) => ({ label: part.label, value: part.id }))" /><label class="image-picker"><ImagePlus :size="17" /><span>{{ newMeal.image ? 'Change image' : 'Add image' }}</span><input type="file" accept="image/*" @change="handleMealImage($event, newMeal)" /></label><img v-if="newMeal.image" :src="mealImageUrl(newMeal.image)" alt="New meal preview" class="meal-preview" /><Button v-if="newMeal.image" quaternary circle type="error" aria-label="Remove new meal image" @click="newMeal.image = null"><X :size="16" /></Button><Button attr-type="submit"><CirclePlus :size="18" /> Add</Button></form><p v-if="imageError" class="form-error">{{ imageError }}</p><div class="option-list"><div v-for="meal in planner.catalog.meals" :key="meal.id" class="option-row"><template v-if="editingOption?.kind === 'meal' && editingOption.originalId === meal.id"><div class="meal-edit-fields"><InputText v-model:value="editingOption.name" aria-label="Edit meal name" /><Select v-model:value="editingOption.type" :options="mealParts.map((part) => ({ label: part.label, value: part.id }))" /><label class="image-picker"><ImagePlus :size="17" /><span>{{ editingOption.image ? 'Change image' : 'Add image' }}</span><input type="file" accept="image/*" @change="handleMealImage($event, editingOption)" /></label><img v-if="editingOption.image" :src="mealImageUrl(editingOption.image)" :alt="`${editingOption.name} preview`" class="meal-preview" /><Button v-if="editingOption.image" quaternary circle type="error" aria-label="Remove meal image" @click="editingOption.image = null"><X :size="16" /></Button></div><Button size="small" @click="commitOptionEdit">Save</Button></template><template v-else><div class="option-identity"><span class="meal-thumb"><img v-if="meal.image" :src="mealImageUrl(meal.image)" alt="" /><CookingPot v-else :size="17" /></span><div><strong>{{ meal.name }}</strong><span>{{ meal.type }}</span></div></div><div class="row-actions"><Button quaternary circle aria-label="Rename meal" @click="startEditOption('meal', meal)"><Pencil :size="16" /></Button><Button quaternary circle type="error" aria-label="Delete meal option" @click="planner.deleteOption('meal', meal.id)"><Trash2 :size="16" /></Button></div></template></div></div></template>
    <section v-if="optionMode === 'integrations'" class="integration-status"><div><p class="period-time"><CalendarDays :size="15" /> Google Calendar</p><h3>{{ planner.googleCalendarIntegration?.status === 'ready' ? 'Connected' : planner.googleCalendarIntegration?.status === 'connected' ? 'Choose a Calendar' : planner.googleCalendarIntegration?.status === 'connecting' ? 'Connecting' : planner.googleCalendarIntegration?.status === 'disconnected' ? 'Ready to connect' : planner.googleCalendarIntegration?.status === 'unavailable' ? 'Unavailable' : 'Status unavailable' }}</h3></div><p>{{ planner.googleCalendarIntegration?.message ?? 'Checking Google Calendar status...' }}</p><p v-if="planner.googleCalendarIntegration?.calendar">Selected Calendar: {{ planner.googleCalendarIntegration.calendar.summary }}</p><p v-if="planner.googleCalendarIntegration?.status === 'unavailable'">Google Calendar is not included in this HomeChore release.</p><template v-if="canManageGoogleCalendar && planner.googleCalendarIntegration?.available"><Button v-if="planner.googleCalendarIntegration.status === 'disconnected'" type="primary" @click="connectGoogleCalendar">Add Google Calendar</Button><template v-else-if="planner.googleCalendarIntegration.status === 'connected'"><Select v-model:value="selectedGoogleCalendar" :options="googleCalendars.map((calendar) => ({ label: calendar.summary, value: calendar.id }))" placeholder="Choose a Calendar" aria-label="Google Calendar" /><div class="modal-actions"><Button secondary :loading="googleCalendarBusy" @click="loadGoogleCalendars">Load calendars</Button><Button type="primary" :disabled="!selectedGoogleCalendar" :loading="googleCalendarBusy" @click="selectGoogleCalendar">Use Calendar</Button></div></template><template v-else-if="planner.googleCalendarIntegration.status === 'ready'"><div class="modal-actions"><Button secondary :loading="googleCalendarBusy" @click="loadGoogleCalendars">Change Calendar</Button><Button type="error" :loading="googleCalendarBusy" @click="disconnectGoogleCalendar">Disconnect</Button></div><template v-if="googleCalendars.length"><Select v-model:value="selectedGoogleCalendar" :options="googleCalendars.map((calendar) => ({ label: calendar.summary, value: calendar.id }))" placeholder="Choose a Calendar" aria-label="Google Calendar" /><Button type="primary" :disabled="!selectedGoogleCalendar" :loading="googleCalendarBusy" @click="selectGoogleCalendar">Use Calendar</Button></template></template></template><p v-if="googleCalendarError" class="form-error">{{ googleCalendarError }}</p></section>
  </NCard></NModal>
</template>