import { useMessage } from 'naive-ui'
import { usePlannerStore } from '../stores/planner'
import { dayName, dayNumber, periodRange, timeLabel } from '../utils/planner'

// Builds PDF exports from the active planner view and its shared Household data.
export function usePdfExport() {
  const planner = usePlannerStore()
  const message = useMessage()
  function drawPdfEmoji(pdf, emoji, x, y, size) { const canvas = document.createElement('canvas'); canvas.width = 64; canvas.height = 64; const context = canvas.getContext('2d'); context.font = '48px sans-serif'; context.fillText(emoji, 6, 50); pdf.addImage(canvas.toDataURL('image/png'), 'PNG', x, y, size, size) }
  function writeHeader(pdf, title, subtitle) { const width = pdf.internal.pageSize.getWidth(); pdf.setFillColor(38, 116, 90); pdf.rect(0, 0, width, 20, 'F'); drawPdfEmoji(pdf, planner.household.icon, 10, 5, 9); pdf.setTextColor(255, 255, 255); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(12); pdf.text('HomeChore', 22, 9); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(8); pdf.text(planner.household.name, 22, 15); pdf.text(title, width - 10, 9, { align: 'right' }); pdf.text(subtitle, width - 10, 15, { align: 'right' }); pdf.setTextColor(38, 51, 47) }
  function writeSettings(pdf, position, width, size) { pdf.setFont('helvetica', 'normal'); pdf.setFontSize(size); const settings = `Assignees: ${planner.household.assignees.join(', ')} | Routine: ${planner.periods.map((period) => `${period.label} ${periodRange(period)}`).join(' | ')}`; const lines = pdf.splitTextToSize(settings, width); pdf.text(lines, 12, position); return position + lines.length * (size * 0.48) + 3 }
  function writeDailyPdf(pdf, day) {
    const width = pdf.internal.pageSize.getWidth(); const bottom = pdf.internal.pageSize.getHeight() - 12; const fontSize = 8; const lineHeight = fontSize * 0.52; let position = 27; let pageFull = false
    writeHeader(pdf, 'Daily plan', `${dayName(day)}, ${dayNumber(day)}`); position = writeSettings(pdf, position, width - 24, 7)
    const availability = planner.availabilityFor(day); if (availability) { pdf.setTextColor(138, 53, 40); pdf.setFontSize(7); pdf.text(availability, 12, position); pdf.setTextColor(38, 51, 47); position += 5 }
    const writeLines = (text, indent = 12, emoji = '') => { if (pageFull) return; pdf.setFont('helvetica', 'normal'); pdf.setFontSize(fontSize); const lines = pdf.splitTextToSize(text, width - indent - 12); const capacity = Math.floor((bottom - position) / lineHeight); if (capacity < 1) { pageFull = true; return }; const visible = lines.slice(0, capacity); if (visible.length < lines.length) { visible[visible.length - 1] = `${visible[visible.length - 1].replace(/\s+$/, '')}...`; pageFull = true }; if (emoji) drawPdfEmoji(pdf, emoji, indent, position - 3.6, 4); pdf.text(visible, indent + (emoji ? 6 : 0), position); position += visible.length * lineHeight + 1.5 }
    for (const period of planner.periods) { if (pageFull || position + 5 > bottom) { pageFull = true; break }; pdf.setFont('helvetica', 'bold'); pdf.setTextColor(38, 116, 90); pdf.setFontSize(9); pdf.text(`${period.label}  ${periodRange(period)}`, 12, position); pdf.setTextColor(38, 51, 47); position += 5; const duties = planner.dutiesFor(day, period.id); if (!duties.length) writeLines('No duties planned', 18); for (const duty of duties) writeLines(`${duty.time ? `${timeLabel(duty.time)} - ` : ''}${duty.name} (${duty.assignee})`, 18, planner.dutyEmoji(duty)) }
    const meals = planner.mealSummary(day); if (meals.length && !pageFull && position + 5 <= bottom) { pdf.setFont('helvetica', 'bold'); pdf.setTextColor(123, 91, 18); pdf.setFontSize(9); pdf.text('Meals', 12, position); pdf.setTextColor(38, 51, 47); position += 5; meals.forEach((meal) => writeLines(`${meal.label}: ${meal.value}`, 18)) }; if (day.notes.trim() && !pageFull && position + 5 <= bottom) { pdf.setFont('helvetica', 'bold'); pdf.setFontSize(9); pdf.text('Notes', 12, position); position += 5; writeLines(day.notes, 18) }; if (pageFull) message.warning('Some detail was shortened to keep this daily plan on one page.')
  }
  function writeWeeklyPdf(pdf) {
    const width = pdf.internal.pageSize.getWidth(); const height = pdf.internal.pageSize.getHeight(); const margin = 7; const gap = 3; const weekdayWidth = (width - margin * 2 - gap * 4) / 5; const weekendWidth = (width - margin * 2 - gap) / 2; const topY = 42; const topHeight = 113; const bottomY = topY + topHeight + gap
    writeHeader(pdf, 'Weekly plan', planner.weekLabel); writeSettings(pdf, 25, width - 24, 6)
    planner.currentWeek.days.forEach((day, index) => {
      const weekend = index > 4; const panelWidth = weekend ? weekendWidth : weekdayWidth; const x = weekend ? margin + (index - 5) * (weekendWidth + gap) : margin + index * (weekdayWidth + gap); const y = weekend ? bottomY : topY; const panelHeight = weekend ? height - bottomY - 7 : topHeight; const bottom = y + panelHeight - 4; let position = y + 14; let full = false
      const writeText = (text, size = weekend ? 10.5 : 9.5, indent = 0, emoji = '') => { if (full) return; pdf.setFont('helvetica', 'normal'); pdf.setFontSize(size); const lines = pdf.splitTextToSize(text, panelWidth - indent - (emoji ? 5 : 0)); const capacity = Math.floor((bottom - position) / (size * 0.5)); if (capacity < 1) { full = true; return }; const visible = lines.slice(0, capacity); if (visible.length < lines.length) { visible[visible.length - 1] = `${visible[visible.length - 1].replace(/\s+$/, '')}...`; full = true }; if (emoji) drawPdfEmoji(pdf, emoji, x + indent, position - 3.8, 4.8); pdf.text(visible, x + indent + (emoji ? 5.5 : 0), position); position += visible.length * size * 0.5 + 2 }
      const heading = (label, fill, text) => { const headingHeight = weekend ? 5.5 : 4.8; if (full || position + headingHeight > bottom) { full = true; return }; pdf.setFillColor(...fill); pdf.rect(x + 2, position - 3.6, panelWidth - 4, weekend ? 5 : 4.4, 'F'); pdf.setFont('helvetica', 'bold'); pdf.setTextColor(...text); pdf.setFontSize(weekend ? 10 : 9); const line = pdf.splitTextToSize(label, panelWidth - 7)[0]; pdf.text(line.length < label.length ? `${line.replace(/\s+$/, '')}...` : line, x + 3, position); pdf.setTextColor(38, 51, 47); position += headingHeight }
      pdf.setFillColor(237, 246, 241); pdf.rect(x, y, panelWidth, panelHeight, 'F'); pdf.setFillColor(38, 116, 90); pdf.rect(x, y, panelWidth, 11, 'F'); pdf.setFont('helvetica', 'bold'); pdf.setTextColor(255, 255, 255); pdf.setFontSize(weekend ? 16 : 13); pdf.text(dayName(day), x + 3, y + 5.5); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(weekend ? 8 : 7); pdf.text(dayNumber(day), x + 3, y + 9.5); pdf.setTextColor(38, 51, 47)
      const availability = planner.availabilityFor(day); if (availability) writeText(availability, weekend ? 9.5 : 8.5, 3); for (const period of planner.periods) { heading(`${period.label} | ${periodRange(period)}`, [215, 234, 225], [38, 116, 90]); if (full) break; const duties = planner.dutiesFor(day, period.id); if (!duties.length) writeText('Open', weekend ? 9.5 : 8.5, 4); duties.forEach((duty) => writeText(`${duty.time ? `${timeLabel(duty.time)} ` : ''}${duty.name} (${duty.assignee})`, weekend ? 10.2 : 9.2, 4, planner.dutyEmoji(duty))) }
      const meals = planner.mealSummary(day); if (meals.length && !full) { heading('Meals', [255, 244, 207], [123, 91, 18]); meals.forEach((meal) => writeText(`${meal.label}: ${meal.value}`, weekend ? 9.5 : 8.5, 4)) }; if (day.notes.trim() && !full) { heading('Notes', [232, 237, 234], [38, 51, 47]); writeText(day.notes, weekend ? 9.5 : 8.5, 4) }
    })
  }
  // Match the active daily or weekly screen to its existing download format.
  async function downloadCurrentPlanPdf() { if (!planner.currentWeek) return; try { const { jsPDF } = await import('jspdf'); if (planner.selectedDay) { const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' }); writeDailyPdf(pdf, planner.selectedDay); pdf.save(`homechore-daily-${planner.selectedDay.date}-${planner.currentWeek.id}.pdf`); return }; const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a3' }); writeWeeklyPdf(pdf); pdf.save(`homechore-weekly-${planner.currentWeek.id}.pdf`) } catch { message.error('Could not create this PDF.') } }
  return { downloadCurrentPlanPdf }
}